### ISSUE TITLE
Design UI Wireframes

### ISSUE THREAD

**Issue by satyakranthi1** [Guess-the-word/Guess-The-Word-Frontend#4]

**Comment by ChaitanyaRishi** [comment]
![game](https://user-images.githubusercontent.com/22749508/84449479-8e512b00-ac1b-11ea-852e-b81fd4d4ac01.png)
![roomalone](https://user-images.githubusercontent.com/22749508/84449487-93ae7580-ac1b-11ea-9718-38bde1bc1aa8.png)

^We finalized these wireframes
